apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: mydomain
  description: MyDomain
spec:
  owner: team-a
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: l33t-service
  description: very professional
spec:
  type: website
  lifecycle: experimental
  owner: guest

